version: "3"
services:
  postgres:
    build: .
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: animal-product-eshop
      TEST_POSTGRES_DB: animal-product-eshop-test
      TZ: Europe/Bratislava
      PGTZ: Europe/Bratislava
    ports:
      - "5432:5432"
    container_name: app_db
