version: "3"
services:
  postgres:
    image: postgres:11
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: animal-product-eshop
      TZ: Europe/Bratislava
      PGTZ: Europe/Bratislava
    ports:
      - "5432:5432"
    container_name: app_db
